apiVersion: fusion.storage.openshift.io/v1alpha1
kind: FusionAccess
metadata:
  name: fusionaccess-sample
  namespace: openshift-fusion-access
spec:
  ibm_cnsa_version: {{ gpfs_cnsa_version }}
  storagedevicediscovery:
    create: true
