apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  name: shareddisk1
  namespace: ibm-spectrum-scale
spec:
  # FIXME(bandini): the stable symlink gets EPERM from gpfs, so for now this will do
  # note that a node reboot might just rename this devices, so...
  device: {{ gpfs_shared_lun }}
  node: {{ worker_nodes[0] }}
  # nodeConnectionSelector defines the nodes that have the shared lun directly attached to them
  nodeConnectionSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/worker
      operator: Exists

  # set below only during testing
  existingDataSkipVerify: true
