apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: ctlplanessharedlun
  namespace: ibm-spectrum-scale
spec:
  # FIXME(bandini): the stable symlink gets EPERM from gpfs, so for now this will do
  # note that a node reboot might just rename this devices, so...
  device: /dev/nvme1n1
  node: {{ worker_nodes[0] }}
  # nodeConnectionSelector defines the nodes that have the shared lun directly attached to them
  nodeConnectionSelector:
    matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      {% for node in worker_nodes %}
      - {{ node }}
      {% endfor %}
  # set below only during testing
  existingDataSkipVerify: true
