apiVersion: v1
kind: Namespace
metadata:
  name: openshift-migration
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtc-operator
  namespace: openshift-migration
spec:
  channel: release-v1.8
  installPlanApproval: Automatic
  name: mtc-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration
  namespace: openshift-migration
spec:
  targetNamespaces:
    - openshift-migration
  upgradeStrategy: Default
