---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-oadp-operator
  namespace: openshift-adp
spec:
spec:
  channel: stable
  installPlanApproval: Automatic
  name: redhat-oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp-operator
  namespace: openshift-adp
spec:
  targetNamespaces:
    - openshift-adp
  upgradeStrategy: Default  

