apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ operator_name }}
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: {{ operator_name }}
  source: test-purplestorage-operator
  sourceNamespace: openshift-marketplace
