apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ operator_name }}
  namespace: {{ operator_namespace }}
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: {{ operator_name }}
  source: test-storage-scale-operator
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: storage-scale-operator-group
  namespace: {{ operator_namespace }}
spec:
  upgradeStrategy: Default
