apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-test-sc2
parameters:
  volBackendFs: {{ gpfs_fs_name_two }}
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
