apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-test-sc
parameters:
  volBackendFs: {{ gpfs_fs_name }}
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
