apiVersion: scale.storage.openshift.io/v1alpha1
kind: StorageScale
metadata:
  name: storagescale-sample
  namespace: openshift-storage-scale
spec:
  mco_config:
    create: true
    labels:
      machineconfiguration.openshift.io/role: "worker"
  ibm_cnsa_cluster:
    create: true
    daemon_nodeSelector:
      node-role.kubernetes.io/worker: ""
  ibm_cnsa_version: {{ gpfs_cnsa_version }}
  storagedevicediscovery:
    create: true
