apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-test-sc
parameters:
  volBackendFs: localfilesystem
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
