---
- name: Destroy SNO cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy ocp cluster
      tags:
        - ocp_destroy
      ansible.builtin.shell: |
        set -e
        pwd
        {{ basefolder }}/{{ ocp_version }}/oc help
      args:
        chdir: "{{ ocpfolder }}"
