---
- name: Playbook to set up the Openshift Cluster
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    # Use this to override stuff that won't be committed to git
    - ./overrides.yml
  tasks:
    - name: Create working folder
      tags:
        - ocp_install
      ansible.builtin.file:
        path: "{{ ocpfolder }}"
        state: directory
        recurse: true

    - name: Template OCP install file
      tags:
        - ocp_install
      ansible.builtin.template:
        src: ../templates/full-cluster-install-config.j2.yaml
        dest: "{{ ocpfolder }}/install-config.yaml"

    - name: Set kubeadmin password fact
      tags:
        - ocp_install
      ansible.builtin.shell: |
        python -c 'import bcrypt; print(bcrypt.hashpw(b"{{ kubeadmin_pass }}", bcrypt.gensalt(rounds=10)).decode())' | base64 -w0
      register:
        hashed_password_out

    - name: Set hashed password fact
      tags:
        - ocp_install
      ansible.builtin.set_fact:
        hashed_password: "{{ hashed_password_out.stdout }}"

    - name: Install ocp cluster
      tags:
        - ocp_install
      ansible.builtin.shell: |
        set -ex
        id
        {{ basefolder }}/{{ ocp_version }}/openshift-install create cluster --dir=. &> /tmp/oc-{{ ocp_version }}-{{ ocp_cluster_name }}.log
      args:
        chdir: "{{ ocpfolder }}"

    - name: Set kubeadmin password
      tags:
        - ocp_install
      ansible.builtin.shell: |
        set -e
        chmod 0600 ./auth/kubeconfig
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} patch secret -n kube-system kubeadmin --type json -p '[{"op": "replace", "path": "/data/kubeadmin", "value": "'{{ hashed_password }}'"}]'
      args:
        chdir: "{{ ocpfolder }}"

    - name: Find OpenShift EC2 Instances
      tags:
        - ebs
      amazon.aws.ec2_instance_info:
        region: "{{ ocp_region }}"
        filters:
          "tag:Name": "{{ ocp_cluster_name }}*master*"
          "instance-state-name": "running"
      register: ec2_workers

    - name: Set EC2 workers instance IDs
      tags:
        - ebs
      ansible.builtin.set_fact:
        worker_ec2_ids: "{{ ec2_workers.instances | map(attribute='instance_id') | list }}"

    - name: Create EBS io2 volume
      tags:
        - ebs
      amazon.aws.ec2_vol:
        region: "{{ ocp_region }}"
        availability_zone: "{{ ocp_az }}"
        volume_size: "{{ ebs_volume_size }}"
        volume_type: "{{ ebs_volume_type }}"
        multi_attach: yes
        iops: "{{ ebs_iops }}"
        tags:
          Name: "{{ gpfs_volume_name }}"
      register: ebs_volume

    - name: Attach EBS volume to workers
      tags:
        - ebs
      amazon.aws.ec2_vol:
        region: "{{ ocp_region }}"
        instance: "{{ item }}"
        id: "{{ ebs_volume.volume_id }}"
        device_name: "{{ ebs_device_name }}"
      loop: "{{ worker_ec2_ids }}"
      when: ebs_volume.volume_id is defined

    - name: Install ibm spectrum manifest
      tags:
        - gpfs
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} apply -f https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-container-native/{{ gpfs_version }}/generated/scale/install.yaml
      args:
        chdir: "{{ ocpfolder }}"

    - name: Create gpfs folder
      tags:
        - gpfs
      ansible.builtin.file:
        path: "{{ gpfsfolder }}"
        state: directory
        recurse: true

    - name: template ocp mirror
      tags:
        - gpfs
      ansible.builtin.template:
        src: ../templates/imagedigestmirror.yaml
        dest: "{{ gpfsfolder }}/imagedigestmirror.yaml"

    - name: Apply mirror template
      tags:
        - gpfs
      ansible.builtin.shell: |
        set -e
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} apply -f "{{ gpfsfolder }}/imagedigestmirror.yaml"
      args:
        chdir: "{{ ocpfolder }}"

    - name: Update global pull secret
      tags:
        - gpfs
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        NEW_PS=$({{ oc_bin }} -n openshift-config get secret pull-secret -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d  | jq -c '.auths += {"quay.io/rhsysdeseng":{"auth":"{{ ibmpullsecret }}", "email":""}}' | base64 -w 0)
        {{ oc_bin }} -n openshift-config patch secret pull-secret -p "{\"data\":{\".dockerconfigjson\":\"$NEW_PS\"}}"
      args:
        chdir: "{{ ocpfolder }}"

    - name: Create ibm secret
      tags:
        - gpfs
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        cat <<EOF > {{ gpfsfolder }}/ibmscaleps.json
        {"auths":{"quay.io/rhsysdeseng":{"auth":"{{ ibmpullsecret }}","email":""}}}
        EOF
        for namespace in ibm-spectrum-scale ibm-spectrum-scale-operator ibm-spectrum-scale-dns ibm-spectrum-scale-csi; do
          {{ oc_bin }} create secret docker-registry ibm-entitlement-key -n ${namespace} --from-file=.dockerconfigjson={{ gpfsfolder }}/ibmscaleps.json
        done
      args:
        chdir: "{{ ocpfolder }}"

    - name: Template files
      tags:
        - gpfs
      ansible.builtin.template:
        src: ../templates/{{ item }}
        dest: "{{ gpfsfolder }}/{{ item }}"
      loop:
        - mco.yaml
        - cluster.yaml

    - name: Apply MCO template
      tags:
        - gpfs
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} apply -f {{ gpfsfolder }}/mco.yaml
      args:
        chdir: "{{ ocpfolder }}"

    - name: Wait for MCP to settle
      tags:
        - gpfs2
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        if [ $({{ oc_bin }} get mcp/master -o jsonpath='{.status.readyMachineCount}') != $({{ oc_bin }} get mcp/master -o jsonpath='{.status.machineCount}') ]; then
          exit 1
        fi
        if [ $({{ oc_bin }} get mcp/worker -o jsonpath='{.status.readyMachineCount}') != $({{ oc_bin }} get mcp/worker -o jsonpath='{.status.machineCount}') ]; then
          exit 1
        fi
      args:
        chdir: "{{ ocpfolder }}"
      retries: 30
      delay: 20
      register: mcp_ready
      until: mcp_ready is not failed

    - name: Label the workers
      tags:
        - gpfs2
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        for node in $({{ oc_bin }} get nodes -l node-role.kubernetes.io/master -o name)
        do
          {{ oc_bin }} label ${node} scale.spectrum.ibm.com/role=storage
          {{ oc_bin }} label ${node} scale.spectrum.ibm.com/daemon-selector=""
        done
      args:
        chdir: "{{ ocpfolder }}"

    - name: Apply the cluster template
      tags:
        - gpfs2
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} apply -f "{{ gpfsfolder }}/cluster.yaml"
      args:
        chdir: "{{ ocpfolder }}"

    - name: Get the Volume ID by Tag Name again
      tags:
        - gpfs3
      amazon.aws.ec2_vol_info:
        region: "{{ ocp_region }}"
        filters:
          "tag:Name": "{{ gpfs_volume_name }}"
      register: volume_info

    - name: Fail if there is not exactly one ebs volume
      tags:
        - gpfs3
      ansible.builtin.fail:
        msg: "There must be only one ebs volumes called {{ gpfs_volume_name }}: {{ volume_info }}"
      when: volume_info.volumes | length != 1

    - name: Set volumeid fact
      tags:
        - gpfs3
      ansible.builtin.set_fact:
        ebs_volid: "{{ volume_info.volumes[0].volume_id }}"

    - name: Get worker nodes names
      tags:
        - gpfs3
      ansible.builtin.shell: |
        export KUBECONFIG=./auth/kubeconfig
        {{ oc_bin }} get nodes -l node-role.kubernetes.io/master -o name | cut -f2 -d/
      args:
        chdir: "{{ ocpfolder }}"
      register: worker_nodes_output

    - name: Set worker nodes names fact
      tags:
        - gpfs3
      ansible.builtin.set_fact:
        worker_nodes: "{{ worker_nodes_output.stdout_lines }}"

    - name: Template the localdisk
      tags:
        - gpfs3
      ansible.builtin.template:
        src: ../templates/localdisk.yaml
        dest: "{{ gpfsfolder }}/localdisk.yaml"
