---
- name: Mirror all tools listed in ocp_versions
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: Create mirror folders
      ansible.builtin.file:
        path: "{{ basefolder }}/{{ ocp_version }}"
        state: directory
        recurse: true

    - name: Set OC facts to download bits (Mac OSX)
      ansible.builtin.set_fact:
        oc_client_url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-client-mac-arm64.tar.gz"
        oc_install_url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-install-mac-arm64.tar.gz"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Set OC facts to download bits (Linux)
      ansible.builtin.set_fact:
        oc_client_url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-client-linux.tar.gz"
        oc_install_url: "{{ openshift_mirror }}/{{ ocp_version }}/openshift-install-linux.tar.gz"
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"

    - name: Print URLs
      ansible.builtin.debug:
        msg: "URL to be used: {{ oc_client_url }} - {{ oc_install_url }}"

    - name: Download oc
      ansible.builtin.get_url:
        url: "{{ oc_client_url }}"
        dest: "{{ basefolder }}/{{ ocp_version }}/openshift-client.tar.gz"
        mode: "0640"
      environment:
        https_proxy: "{{ https_proxy | default('') }}"

    - name: Download openshift-install
      ansible.builtin.get_url:
        url: "{{ oc_install_url }}"
        dest: "{{ basefolder }}/{{ ocp_version }}/openshift-install.tar.gz"
        mode: "0640"
      environment:
        https_proxy: "{{ https_proxy | default('') }}"

    - name: Uncompress oc
      ansible.builtin.unarchive:
        src: "{{ basefolder }}/{{ ocp_version }}/openshift-client.tar.gz"
        dest: "{{ basefolder }}/{{ ocp_version }}"
        remote_src: true

    - name: Uncompress openshift install
      ansible.builtin.unarchive:
        src: "{{ basefolder }}/{{ ocp_version }}/openshift-install.tar.gz"
        dest: "{{ basefolder }}/{{ ocp_version }}"
        remote_src: true
