- name: Create gpfs folder
  tags:
    - 4_operator
  ansible.builtin.file:
    path: "{{ gpfsfolder }}"
    state: directory
    recurse: true

- name: Template catalogsource
  ansible.builtin.template:
    src: ../templates/operator-catalog.yaml
    dest: "{{ gpfsfolder }}/operator-catalog.yaml"
    mode: "0644"
  tags:
    - 4_operator

- name: Apply catalog
  tags:
    - 4_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG={{ kubeconfig }}
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/operator-catalog.yaml"

- name: Template subscription
  ansible.builtin.template:
    src: ../templates/operator-subscription.yaml
    dest: "{{ gpfsfolder }}/operator-subscription.yaml"
  tags:
    - 4_operator

- name: Apply subscription
  tags:
    - 4_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG={{ kubeconfig }}
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/operator-subscription.yaml"
  retries: 10
  delay: 20
  register: subscription_ready
  until: subscription_ready is not failed

- name: Create the fusion-pullsecret
  tags:
    - 4_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG={{ kubeconfig }}
    {{ oc_bin }} delete secret -n openshift-fusion-access fusion-pullsecret || true
    {{ oc_bin }} create secret -n openshift-fusion-access generic fusion-pullsecret  \
      --from-literal=ibm-entitlement-key={{ ibmentitlementkey }}
  retries: 10
  delay: 20
  register: secret_ready
  until: secret_ready is not failed

- name: Template fusionaccess
  ansible.builtin.template:
    src: ../templates/fusionaccess.yaml
    dest: "{{ gpfsfolder }}/fusionaccess.yaml"
  tags:
    - 5_operator

- name: Apply fusionaccess
  tags:
    - 5_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG={{ kubeconfig }}
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/fusionaccess.yaml"
  retries: 15
  delay: 30
  register: fusionaccess_ready
  until: fusionaccess_ready is not failed
