- name: Create gpfs folder
  tags:
    - 4_gpfs
  ansible.builtin.file:
    path: "{{ gpfsfolder }}"
    state: directory
    recurse: true

- name: Template catalogsource
  ansible.builtin.template:
    src: ../templates/operator-catalog.yaml
    dest: "{{ gpfsfolder }}/operator-catalog.yaml"
  tags:
    - 4_operator

- name: Apply catalog
  tags:
    - 4_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG=./auth/kubeconfig
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/operator-catalog.yaml"
  args:
    chdir: "{{ ocpfolder }}"

- name: Template subscription
  ansible.builtin.template:
    src: ../templates/operator-subscription.yaml
    dest: "{{ gpfsfolder }}/operator-subscription.yaml"
  tags:
    - 4_operator

- name: Apply subscription
  tags:
    - 4_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG=./auth/kubeconfig
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/operator-subscription.yaml"
  retries: 10
  delay: 20
  register: subscription_ready
  until: subscription_ready is not failed
  args:
    chdir: "{{ ocpfolder }}"

- name: Template storagescale
  ansible.builtin.template:
    src: ../templates/storagescale.yaml
    dest: "{{ gpfsfolder }}/storagescale.yaml"
  tags:
    - 5_operator

- name: Apply storagescale
  tags:
    - 5_operator
  ansible.builtin.shell: |
    set -e
    export KUBECONFIG=./auth/kubeconfig
    {{ oc_bin }} apply -f "{{ gpfsfolder }}/storagescale.yaml"
  retries: 10
  delay: 20
  register: storagescale_ready
  until: storagescale_ready is not failed
  args:
    chdir: "{{ ocpfolder }}"
